// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const toNonEmpty = (value: string | undefined): string | null => {
  const normalized = value?.trim();
  return normalized ? normalized : null;
};

const SUPABASE_URL = toNonEmpty(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = toNonEmpty(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

export const supabaseConfigError =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? "Missing Supabase configuration. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseUrl = SUPABASE_URL ?? "https://invalid.supabase.co";
const supabasePublishableKey = SUPABASE_PUBLISHABLE_KEY ?? "invalid-publishable-key";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
